### ISSUE TITLE
Intercom DDS binary cannot be run in Ubuntu 20.04

### ISSUE THREAD

**Issue by MiguelCompany** [omg-dds/dds-rtps#33]
Running the binary uploaded to [Automatic Interoperability Test v1.1.2024](https://github.com/omg-dds/dds-rtps/releases/tag/v1.1.2024) on a fresh Ubuntu 20.04 docker container produces the following error:

``` bash
$ ./intercom_dds-3.16.2.0_shape_main_linux
./intercom_dds-3.16.2.0_shape_main_linux: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by ./intercom_dds-3.16.2.0_shape_main_linux)
$ 
```

The rest of the binaries work well.

[This section](https://github.com/omg-dds/dds-rtps?tab=readme-ov-file#upload-executable) of the readme states a requirement on the executable to run in Ubuntu 20.04, but the workflow runs on [ubuntu-latest](https://github.com/omg-dds/dds-rtps/actions/runs/8364904085/workflow#L6)

So I think we should decide whether we keep requiring Ubuntu 20.04 (and then Intercom DDS should be built and uploaded again) or change the requirement to Ubuntu 22.04.

In any case, the final requirement should be enforced by changing the workflow to run in the minimum required OS version.

**Comment by angelrti** [comment]
@MiguelCompany in the last DDS-SIP we agreed to move to Ubuntu 22.04, so probably we can close this issue
