### ISSUE TITLE
Upload executable for Dust DDS

### ISSUE THREAD

**Issue by stkimmer** [omg-dds/dds-rtps#49]
We have created an executable that follows the interface mentioned in the read-me. We also ran our executable against the Connext DDS executable and generated a report. All tests are passing. The report and the steps that were executed can be seen here: https://github.com/s2e-systems/dust-dds/actions/runs/10385346755/job/28754286361#step:14:20

How can we upload the executable here? The steps mentioned in the read-me require more permissions.

**Comment by angelrti** [comment]
Hello stkimmer, great to hear that!
Please follow the instructions in the [CONTRIBUTING](https://github.com/omg-dds/dds-rtps/blob/master/CONTRIBUTING.md) file and do the pull request for the CLA_S2E_SoftwareSystems.md
After this we will grant you wrote privilege to the repository. You should then upload the source code for your test under a new directory called srcRs/DustDDS.
You will also need to [draft a new release](https://github.com/omg-dds/dds-rtps/releases) and upload your executable there.
Once this is done we will circle back and figure our how to best integrate it into the automatically-generated reports.

**Comment by stkimmer** [comment]
I created the draft release: https://github.com/omg-dds/dds-rtps/releases/tag/untagged-0151398a65c365723b05

**Comment by MiguelCompany** [comment]
> I created the draft release: https://github.com/omg-dds/dds-rtps/releases/tag/untagged-0151398a65c365723b05

@stkimmer @angelrti I took the zip file from this draft release and had the following issues running the tests in my fork of this repo.

- The executable contained in the zip file does not have execution permissions and thus fails to be executed in the CI
- After fixing that locally (by extracting the file, running `chmod a+x dust_dds-0.11.0_shape_main_linux` and zipping the file again), the report generation step failed when trying to get the company name

The failure seems to stem from the fact that `get_company_name` uses the result of `get_product_name` as input.
The product name for `dust_dds-xxx` executables results in `Dust DDS`, but  `get_company_name` is looking for `dust_dds` [here](https://github.com/omg-dds/dds-rtps/blob/master/generate_xlsx_report.py#L64). So either we change the value returned by `get_product_name`, or we change the condition in `get_company_name`

_PS: All tests passed between Dust DDS and Fast DDS_

**Comment by stkimmer** [comment]
Thanks for your effort. 
- I updated the executable in the zip file of the draft release. It should now contain the executable permission flag. 
- I created a PR #53 that fixed the issue with the report generation

**Comment by stkimmer** [comment]
@angelrti (@MiguelCompany) Could you let me what are the next steps to "integrate it into the automatically-generated reports"?

**Comment by angelrti** [comment]
@stkimmer I will have a look at this tomorrow and get back to you if I find something. If not, I'll go ahead and move the executable to the right release to generate the report

**Comment by angelrti** [comment]
It looks good to me. There is one test that is not working properly (https://github.com/omg-dds/dds-rtps/pull/54). After merging this fix I will copy your executable to the current release and run the tests in GitHub Actions

**Comment by angelrti** [comment]
@stkimmer I have run the tests, here you can find the preliminary results https://github.com/omg-dds/dds-rtps/actions/runs/10792524742
